NSString *DUMMY_USERNAME = @"raxy09@gmail.com";
NSString *DUMMY_PASSWORD = @"myngqxw8";

NSString *FACEBOOK_PASSWORD = @"eMagFB01$User";

NSString	*USER_LOGIN_FINISHED 			= @"USER_LOGIN_FINISHED";
NSString	*USER_LOGIN_FAILED              = @"USER_LOGIN_FAILED";

NSString	*USER_LOGIN_FACEBOOK_FINISHED 			= @"USER_LOGIN_FACEBOOK_FINISHED";
NSString	*USER_LOGIN_FACEBOOK_FAILED              = @"USER_LOGIN_FACEBOOK_FAILED";

NSString	*USER_REGISTER_FINISHED 			= @"USER_REGISTER_FINISHED";
NSString	*USER_REGISTER_FAILED              = @"USER_REGISTER_FAILED";

NSString	*ADD_EVENT_FINISHED 			= @"ADD_EVENT_FINISHED";
NSString	*ADD_EVENT_FAILED              = @"ADD_EVENT_FAILED";

NSString	*GET_NOTIFICATIONS_FINISHED 			= @"GET_NOTIFICATIONS_FINISHED";
NSString	*GET_NOTIFICATIONS_FAILED              = @"GET_NOTIFICATIONS_FAILED";

NSString	*NOTIFICATION_DETAIL_FINISHED 			= @"NOTIFICATION_DETAIL_FINISHED";
NSString	*NOTIFICATION_DETAIL_FAILED              = @"NOTIFICATION_DETAIL_FAILED";

NSString	*GET_EVENTS_FINISHED 			= @"GET_EVENTS_FINISHED";
NSString	*GET_EVENTS_FAILED              = @"GET_EVENTS_FAILED";

NSString	*PASSWORD_RECOVER_FINISHED 			= @"PASSWORD_RECOVER_FINISHED";
NSString	*PASSWORD_RECOVER_FAILED            = @"PASSWORD_RECOVER_FAILED";

NSString	*GET_COMMENTS_FINISHED 			= @"GET_COMMENTS_FINISHED";
NSString	*GET_COMMENTS_FAILED              = @"GET_COMMENTS_FAILED";

NSString	*GET_EVENTS_COMMENTS_FINISHED 			= @"GET_EVENTS_COMMENTS_FINISHED";
NSString	*GET_EVENTS_COMMENTS_FAILED              = @"GET_EVENTS_COMMENTS_FAILED";

NSString	*GET_EVENTS_COMMENTS_COUNT_FINISHED 			= @"GET_EVENTS_COMMENTS_COUNT_FINISHED";
NSString	*GET_EVENTS_COMMENTS_COUNT_FAILED              = @"GET_EVENTS_COMMENTS_COUNT_FAILED";

NSString	*ADD_COMMENTS_FINISHED 			= @"ADD_COMMENTS_FINISHED";
NSString	*ADD_COMMENTS_FAILED              = @"ADD_COMMENTS_FAILED";

NSString	*ADD_EVENT_COMMENTS_FINISHED 			= @"ADD_EVENT_COMMENTS_FINISHED";
NSString	*ADD_EVENT_COMMENTS_FAILED              = @"ADD_EVENT_COMMENTS_FAILED";

NSString	*UPDATE_PROFILE_FINISHED 			= @"UPDATE_PROFILE_FINISHED";
NSString	*UPDATE_PROFILE_FAILED              = @"UPDATE_PROFILE_FAILED";

NSString	*GET_LIST_ALARM_FINISHED 			= @"GET_LIST_ALARM_FINISHED";
NSString	*GET_LIST_ALARM_FAILED              = @"GET_LIST_ALARM_FAILED";

NSString	*GET_COUNTRYNUMBER_FINISHED 			= @"GET_COUNTRYNUMBER_FINISHED";
NSString	*GET_COUNTRYNUMBER_FAILED              = @"GET_COUNTRYNUMBER_FAILED";

NSString	*GET_ADDALARM_FINISHED 			= @"GET_ADDALARM_FINISHED";
NSString	*GET_ADDALARM_FAILED              = @"GET_ADDALARM_FAILED";

NSString	*GET_UPDATEALARM_FINISHED 			= @"GET_UPDATEALARM_FINISHED";
NSString	*GET_UPDATEALARM_FAILED              = @"GET_UPDATEALARM_FAILED";

NSString	*GET_DELETEALARM_FINISHED 			= @"GET_DELETEALARM_FINISHED";
NSString	*GET_DELETEALARM_FAILED              = @"GET_DELETEALARM_FAILED";

NSString	*GET_PEOPLE_LOCATION_DETAILS_FINISHED = @"GET_PEOPLE_LOCATION_DETAILS_FINISHED";
NSString	*GET_PEOPLE_LOCATION_DETAILS_FAILED   = @"GET_PEOPLE_LOCATION_DETAILS_FAILED";

NSString	*GET_LIST_GROUP_FINISHED 			= @"GET_LIST_GROUP_FINISHED";
NSString	*GET_LIST_GROUP_FAILED              = @"GET_LIST_GROUP_FAILED";

NSString	*GET_DELETEGROUP_FINISHED 			= @"GET_DELETEGROUP_FINISHED";
NSString	*GET_DELETEGROUP_FAILED              = @"GET_DELETEGROUP_FAILED";

NSString	*ADD_GROUP_FINISHED 			= @"ADD_GROUP_FINISHED";
NSString	*ADD_GROUP_FAILED              = @"ADD_GROUP_FAILED";

NSString	*GET_GROUPCONTACTS_FINISHED 			= @"GET_GROUPCONTACTS_FINISHED";
NSString	*GET_GROUPCONTACTS_FAILED              = @"GET_GROUPCONTACTS_FAILED";

NSString	*ADD_CONTACT_GROUP_FINISHED 			= @"ADD_CONTACT_GROUP_FINISHED";
NSString	*ADD_CONTACT_GROUP_FAILED              = @"ADD_CONTACT_GROUP_FAILED";

NSString	*DELETE_PERSON_FINISHED 			= @"DELETE_PERSON_FINISHED";
NSString	*DELETE_PERSON_FAILED              = @"DELETE_PERSON_FAILED";

NSString	*USER_HAS_APP_FINISHED 			= @"USER_HAS_APP_FINISHED";
NSString	*USER_HAS_APP_FAILED              = @"USER_HAS_APP_FAILED";

NSString	*ACCEPT_INVITE_FINISHED 			= @"ACCEPT_INVITE_FINISHED";
NSString	*ACCEPT_INVITE_FAILED              = @"ACCEPT_INVITE_FAILED";

NSString	*GROUP_MAP_FINISHED 			= @"GROUP_MAP_FINISHED";
NSString	*GROUP_MAP_FAILED              = @"GROUP_MAP_FAILED";

NSString	*GET_ALARMSETTINGS_FINISHED 			= @"GET_ALARMSETTINGS_FINISHED";
NSString	*GET_ALARMSETTINGS_FAILED              = @"GET_ALARMSETTINGS_FAILED";

NSString	*SAVE_ALARMSETTINGS_FINISHED 			= @"SAVE_ALARMSETTINGS_FINISHED";
NSString	*SAVE_ALARMSETTINGS_FAILED              = @"SAVE_ALARMSETTINGS_FAILED";

NSString    *TERMS_OF_USE = @"http://viaparquerimac.com.pe/es/Terminos_de_Uso.pdf";


//NSString *lServiceURL = @"http://emaguenwcfm3.cloudapp.net/JsonService.svc/";
//NSString *lServiceURL = @"http://emaguen.cloudapp.net/JsonService.svc/";
NSString *lServiceURL = @"http://emaguenv2.cloudapp.net/JsonService.svc/";